"""Cron job schedule generation.

Generates crontab entries for all periodic tasks.
Pure string generation, no dependencies on running services.
"""
from pathlib import Path


def build_crontab(repo_root: Path) -> str:
    """Build crontab file content."""
    return f"""# Satellite Paraguay - Cron Jobs
# Generated by src/utils/crontab_gen.py
# Install: crontab scripts/crontab.txt
#
# Schedule legend:
#   m h dom mon dow command

# ====== Hourly: Quick health check ======
0 * * * * cd {repo_root} && python3 scripts/alert_cron_failures.py --since-hours=2 >> logs/cron_hourly.log 2>&1

# ====== Daily: Update data, run analysis ======
30 2 * * * cd {repo_root} && python3 scripts/verify_reproducibility.py >> logs/cron_daily.log 2>&1

# ====== Weekly: Full pipeline run (Sunday 06:00 UTC) ======
0 6 * * 0 cd {repo_root} && bash scripts/weekly_run.sh >> logs/cron_weekly.log 2>&1

# ====== Monthly: Dependency audit + cleanup (1st of month) ======
0 4 1 * * cd {repo_root} && python3 scripts/audit_dependencies.py >> logs/cron_monthly.log 2>&1

# ====== Quarterly: Performance benchmarks + report ======
0 5 1 */3 * cd {repo_root} && python3 -m pytest tests/test_performance.py -m performance --no-cov --benchmark-only --benchmark-autosave >> logs/cron_quarterly.log 2>&1

# ====== Hourly: Log rotation (prevent disk fill) ======
0 * * * * cd {repo_root} && find logs/ -name "*.log" -mtime +7 -delete && find outputs/weekly -name "*.log" -mtime +30 -delete

# ====== Daily: Backup outputs to remote ======
0 23 * * * cd {repo_root} && tar czf /tmp/satellite-paraguay-$(date +\\\\%Y\\\\%m\\\\%d).tar.gz outputs/ && (rsync -avz /tmp/satellite-paraguay-$(date +\\\\%Y\\\\%m\\\\%d).tar.gz remote:/backups/ || echo "Backup failed" >> logs/cron_daily.log)
"""


def schedule_summary() -> str:
    """Human-readable summary of cron schedules."""
    return """Cron schedule:
  - Hourly: Health check
  - Daily 02:30 UTC: Reproducibility check
  - Weekly Sunday 06:00 UTC: Full pipeline
  - Monthly 1st 04:00 UTC: Dependency audit
  - Quarterly 1st 05:00 UTC: Performance benchmarks
  - Hourly: Log rotation
  - Daily 23:00 UTC: Backup outputs"""


def write_crontab(repo_root: Path) -> Path:
    """Generate and write crontab file. Returns path to file."""
    out_path = repo_root / "scripts/crontab.txt"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(build_crontab(repo_root))
    return out_path