"""Cron job scheduler for satellite-paraguay.

Generates crontab entries for all periodic tasks.

Run: python3 scripts/generate_crontab.py
"""

from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent


def generate_crontab():
    """Generate crontab file."""
    crontab = """# Satellite Paraguay - Cron Jobs
# Generated by scripts/generate_crontab.py
# Install: crontab scripts/crontab.txt
#
# Schedule legend:
#   m h dom mon dow command

# ====== Hourly: Quick health check ======
0 * * * * cd {REPO_ROOT} && python3 scripts/alert_cron_failures.py --since-hours=2 >> logs/cron_hourly.log 2>&1

# ====== Daily: Update data, run analysis ======
30 2 * * * cd {REPO_ROOT} && python3 scripts/verify_reproducibility.py >> logs/cron_daily.log 2>&1

# ====== Weekly: Full pipeline run (Sunday 06:00 UTC) ======
0 6 * * 0 cd {REPO_ROOT} && bash scripts/weekly_run.sh >> logs/cron_weekly.log 2>&1

# ====== Monthly: Dependency audit + cleanup (1st of month) ======
0 4 1 * * cd {REPO_ROOT} && python3 scripts/audit_dependencies.py >> logs/cron_monthly.log 2>&1

# ====== Quarterly: Performance benchmarks + report ======
0 5 1 */3 * cd {REPO_ROOT} && python3 -m pytest tests/test_performance.py -m performance --no-cov --benchmark-only --benchmark-autosave >> logs/cron_quarterly.log 2>&1  # noqa: E501

# ====== Hourly: Log rotation (prevent disk fill) ======
0 * * * * cd {REPO_ROOT} && find logs/ -name "*.log" -mtime +7 -delete && find outputs/weekly -name "*.log" -mtime +30 -delete  # noqa: E501

# ====== Daily: Backup outputs to remote ======
0 23 * * * cd {REPO_ROOT} && tar czf /tmp/satellite-paraguay-$(date +\\%Y\\%m\\%d).tar.gz outputs/ && (rsync -avz /tmp/satellite-paraguay-$(date +\\%Y\\%m\\%d).tar.gz remote:/backups/ || echo "Backup failed" >> logs/cron_daily.log)  # noqa: E501
""".format(REPO_ROOT=str(REPO_ROOT))

    out_path = REPO_ROOT / "scripts/crontab.txt"
    out_path.write_text(crontab)
    print(f"Generated: {out_path}")
    print("\nTo install:")
    print(f"  crontab {out_path}")
    print("\nCron schedule:")
    print("  - Hourly: Health check")
    print("  - Daily 02:30 UTC: Reproducibility check")
    print("  - Weekly Sunday 06:00 UTC: Full pipeline")
    print("  - Monthly 1st 04:00 UTC: Dependency audit")
    print("  - Quarterly 1st 05:00 UTC: Performance benchmarks")
    print("  - Hourly: Log rotation")
    print("  - Daily 23:00 UTC: Backup outputs")


def main():
    print("=" * 70)
    print("CRON JOB SCHEDULER")
    print("=" * 70)
    generate_crontab()


if __name__ == "__main__":
    main()
