#!/usr/bin/env python3
"""
Merge thesis/references.bib + papers/references.bib into a single references.bib.

Behavior:
  - Entries with the same BibTeX key + identical body text: kept once.
  - Entries with the same key but different body text: resolved per the
    PREFER_PAPERS set (see below); no CONFLICTS section is emitted.
  - Entries unique to either source: included as-is.
  - Output is deterministically sorted by key for diff-friendly regeneration.

Usage:
  python scripts/merge_bib.py [--out PATH]

Default output: ./references.bib (repo root).
"""
from __future__ import annotations
import argparse
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


PREFER_PAPERS = {
    # Manually resolved 2026-08-11: prefer the more descriptive version.
    # To change a preference, edit this set and re-run the script.
    # All 5 are institutional/official citations where the papers version
    # has a slightly more informative title (e.g., includes the acronym
    # in parentheses) and the author field is more granular. The papers
    # version also uses "\url{...}" instead of the malformed "\\\\url{...}"
    # that appears in some thesis entries.
    "indi2024",          # papers: title contains "(INDI)" + author is "INDI Paraguay"
    "infona2024",        # papers: title contains "(INFONA)" + author is "INFONA Paraguay"
    "mades2024",         # papers: title contains "(MADES)" + author is "MADES Paraguay"
    "openaq2024",        # papers: title contains "Open Air Quality Data"
    "tensorflow2015",    # papers: full author list + @software entry type + URL
}


def normalize_entry(entry: str) -> str:
    r"""Sanitize common BibTeX escape artifacts from upstream .bib files.

    These artifacts ("\\url" instead of "\url", "{\'\i}" instead of
    "{\'{\i}}") come from a previous parser that double-escaped special
    characters. They would compile under latex but show as literal
    backslashes in any markdown/PDF renderer. Applied uniformly so future
    merges stay clean.
    """
    out = re.sub(r"\\\\url", r"\\url", entry)
    out = re.sub(r"\'\\i", r"\\'{i}", out)
    return out


def split_entries(text: str) -> list[str]:
    """Split a .bib file into a list of entry strings, one per @entry{...} block."""
    text = re.sub(r"(?m)^%.*$", "", text)
    out: list[str] = []
    depth = 0
    start: int | None = None
    for i, ch in enumerate(text):
        if ch == "{":
            if depth == 0:
                j = text.rfind("@", 0, i)
                if j >= 0:
                    start = j
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start is not None:
                out.append(text[start : i + 1])
                start = None
    return [normalize_entry(e) for e in out if e.strip()]


def entry_key(entry: str) -> str | None:
    m = re.match(r"@\w+\{\s*([^,\s]+)", entry)
    return m.group(1) if m else None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(REPO / "references.bib"))
    args = ap.parse_args()

    thesis_bib = (REPO / "thesis" / "references.bib").read_text(encoding="utf-8")
    papers_bib = (REPO / "papers" / "references.bib").read_text(encoding="utf-8")

    thesis = {k: e for e in split_entries(thesis_bib) if (k := entry_key(e))}
    papers = {k: e for e in split_entries(papers_bib) if (k := entry_key(e))}

    shared = set(thesis) & set(papers)
    diff = [k for k in shared if thesis[k].strip() != papers[k].strip()]
    identical = len(shared) - len(diff)
    unresolved = [k for k in diff if k not in PREFER_PAPERS]

    header = (
        "% Unified references.bib for SatelliteCV-Paraguay\n"
        "% Generated by scripts/merge_bib.py -- DO NOT EDIT BY HAND.\n"
        "%\n"
        "% Provenance:\n"
        f"%   - thesis/references.bib : {len(thesis)} entries\n"
        f"%   - papers/references.bib : {len(papers)} entries\n"
        f"%   - shared (identical)    : {identical} (kept once)\n"
        f"%   - shared (differing)    : {len(diff)} (resolved via PREFER_PAPERS)\n"
        "%\n"
        "% To resolve a new conflict: add the key to PREFER_PAPERS at the top of\n"
        "% this script and re-run. The CONFLICTS section was retired 2026-08-10\n"
        "% after manual review.\n"
        "%\n"
        "% Regenerate with:  python scripts/merge_bib.py\n%\n\n"
    )

    parts = [header, "% ===== UNIQUE ENTRIES (alphabetical by key) =====\n\n"]
    for k in sorted(set(thesis) | set(papers)):
        if k in PREFER_PAPERS and k in papers:
            parts.append(papers[k].rstrip() + "\n\n")
        elif k in thesis:
            parts.append(thesis[k].rstrip() + "\n\n")
        else:
            parts.append(papers[k].rstrip() + "\n\n")

    if unresolved:
        # Fail loud if a new conflict appears that wasn't anticipated.
        raise SystemExit(
            f"ERROR: {len(unresolved)} unresolved bibliography conflicts: {unresolved}\n"
            f"Add them to PREFER_PAPERS in scripts/merge_bib.py after manual review."
        )

    Path(args.out).write_text("".join(parts), encoding="utf-8")

    print(
        f"merged {len(thesis)} + {len(papers)} -> "
        f"{len(set(thesis) | set(papers))} unique entries "
        f"({len(diff)} resolved, 0 unresolved)"
    )
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())