#!/usr/bin/env python3
"""
Merge thesis/references.bib + papers/references.bib into a single references.bib.

Behavior:
  - Entries with the same BibTeX key + identical body text: kept once.
  - Entries with the same key but different body text: thesis version kept as
    canonical, papers version appended under "% CONFLICTS" for manual review.
  - Entries unique to either source: included as-is.
  - Output is deterministically sorted by key for diff-friendly regeneration.

Usage:
  python scripts/merge_bib.py [--out PATH]

Default output: ./references.bib (repo root).
"""
from __future__ import annotations
import argparse
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def split_entries(text: str) -> list[str]:
    """Split a .bib file into a list of entry strings, one per @entry{...} block."""
    text = re.sub(r"(?m)^%.*$", "", text)
    out: list[str] = []
    depth = 0
    start: int | None = None
    for i, ch in enumerate(text):
        if ch == "{":
            if depth == 0:
                j = text.rfind("@", 0, i)
                if j >= 0:
                    start = j
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start is not None:
                out.append(text[start : i + 1])
                start = None
    return [e for e in out if e.strip()]


def entry_key(entry: str) -> str | None:
    m = re.match(r"@\w+\{\s*([^,\s]+)", entry)
    return m.group(1) if m else None


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(REPO / "references.bib"))
    args = ap.parse_args()

    thesis_bib = (REPO / "thesis" / "references.bib").read_text(encoding="utf-8")
    papers_bib = (REPO / "papers" / "references.bib").read_text(encoding="utf-8")

    thesis = {k: e for e in split_entries(thesis_bib) if (k := entry_key(e))}
    papers = {k: e for e in split_entries(papers_bib) if (k := entry_key(e))}

    shared = set(thesis) & set(papers)
    diff = [k for k in shared if thesis[k].strip() != papers[k].strip()]
    identical = len(shared) - len(diff)

    header = (
        "% Unified references.bib for SatelliteCV-Paraguay\n"
        "% Generated by scripts/merge_bib.py — DO NOT EDIT BY HAND below the "
        "conflicts section.\n"
        "%\n"
        "% Provenance:\n"
        f"%   - thesis/references.bib : {len(thesis)} entries\n"
        f"%   - papers/references.bib : {len(papers)} entries\n"
        f"%   - shared (identical)    : {identical} (kept once)\n"
        f"%   - shared (differing)    : {len(diff)} (thesis canonical, papers listed below)\n"
        "%\n"
        "% Regenerate with:  python scripts/merge_bib.py\n%\n\n"
    )

    parts = [header, "% ===== UNIQUE ENTRIES (alphabetical by key) =====\n\n"]
    for k in sorted(set(thesis) | set(papers)):
        if k in thesis:
            parts.append(thesis[k].rstrip() + "\n\n")
        else:
            parts.append(papers[k].rstrip() + "\n\n")

    if diff:
        parts.append("\n% ===== CONFLICTS (shared key, different entry) =====\n")
        parts.append("% Thesis version kept as canonical above. Papers version shown.\n\n")
        for k in sorted(diff):
            parts.append(f"% --- key: {k} ---\n")
            parts.append(papers[k].rstrip() + "\n\n")

    Path(args.out).write_text("".join(parts), encoding="utf-8")

    print(
        f"merged {len(thesis)} + {len(papers)} -> "
        f"{len(set(thesis) | set(papers))} unique entries ({len(diff)} conflicts)"
    )
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())