"""thesis_sync_watchdog.py — Refresh cross-repo state when satellite-paraguay
or thesis-active has new commits.

This is the second autonomous worker. It runs less frequently than the tick
(every 6 hours vs daily) and does lighter-weight work:
1. Re-runs scripts/validate_data.py and captures the audit JSON.
2. If the audit changed since the last run, regenerates a STATUS.md diff
   note (does NOT overwrite STATUS.md — that requires human review).
3. Cross-references with the substrate repo's PROGRESS.md to detect drift.

Schedule: every 6 hours (4× daily), more frequent than the tick because it
is cheap to run (validate_data.py takes <2s).

Usage:
    python3 scripts/thesis_sync_watchdog.py           # full run
    python3 scripts/thesis_sync_watchdog.py --check   # only check if changed
    python3 scripts/thesis_sync_watchdog.py --emit-prompt  # emit cron prompt
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import cast

REPO_ROOT = Path(__file__).resolve().parent.parent
SUBSTRATE_ROOT = Path("/opt/data/thesis-active")
AUDIT_JSON = REPO_ROOT / "outputs" / "data_audit.json"
WATCHDOG_LOG = REPO_ROOT / "logs" / "thesis_sync_watchdog.log"
DRIFT_NOTE = REPO_ROOT / "outputs" / "drift_note.md"


def _audit_sha() -> str | None:
    """Return a short hash of the current audit JSON, or None if missing."""
    if not AUDIT_JSON.exists():
        return None
    return hashlib.sha256(AUDIT_JSON.read_bytes()).hexdigest()[:16]


def _previous_audit_sha() -> str | None:
    """Return the last-recorded audit hash from the watchdog log."""
    if not WATCHDOG_LOG.exists():
        return None
    last = None
    for line in WATCHDOG_LOG.read_text().splitlines():
        # Last line starting with audit_sha=
        if line.startswith("audit_sha="):
            last = line.split("=", 1)[1].strip()
    return last


def run_audit() -> dict:
    """Run scripts/validate_data.py and parse the resulting JSON."""
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "validate_data.py")],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
        timeout=60,
    )
    if result.returncode not in (0, 1):
        raise RuntimeError(f"validate_data.py exited {result.returncode}: {result.stderr[:300]}")
    return cast(dict, json.loads(AUDIT_JSON.read_text()))


def detect_drift(audit: dict, substrate_progress_mtime: float | None) -> list[str]:
    """Return a list of human-readable drift signals."""
    signals: list[str] = []

    # Signal 1: any dataset went from 'present' to 'missing' or vice versa
    by_status = audit.get("by_status_count", {})
    if by_status.get("missing", 0) > 0:
        signals.append(
            f"⚠️ {by_status['missing']} dataset(s) marked MISSING in audit. "
            f"Review outputs/data_audit.json for details."
        )
    if by_status.get("partial", 0) > 0:
        signals.append(f"⚠️ {by_status['partial']} dataset(s) marked PARTIAL — got < 50% of claimed size.")

    # Signal 2: synthetic files count drifted (a new PLACEHOLDER file appeared?)
    if by_status.get("synthetic", 0) > 3:
        signals.append(
            f"⚠️ {by_status['synthetic']} synthetic/placeholder files in the repo. "
            f"Expected ≤3 (the known P0012 fixtures). Review if higher."
        )

    # Signal 3: substrate PROGRESS.md is fresher than thesis-side STATUS.md?
    substrate_path = SUBSTRATE_ROOT / "PROGRESS.md"
    status_path = REPO_ROOT / "STATUS.md"
    if substrate_path.exists() and status_path.exists():
        sub_mtime = substrate_path.stat().st_mtime
        sta_mtime = status_path.stat().st_mtime
        drift_hours = (sub_mtime - sta_mtime) / 3600
        if drift_hours > 24 * 7:  # 1 week
            signals.append(
                f"ℹ️ substrate PROGRESS.md is {drift_hours / 24:.1f} days fresher "
                f"than thesis STATUS.md. Consider running a STATUS refresh."
            )
    return signals


def write_drift_note(signals: list[str], audit_summary: dict) -> None:
    """Write a human-reviewable drift note (does NOT auto-edit STATUS.md)."""
    DRIFT_NOTE.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines = [
        f"# Thesis sync watchdog drift note — {now}",
        "",
        "This file is auto-generated by `scripts/thesis_sync_watchdog.py`. ",
        "It is **informational** — STATUS.md is NOT auto-edited. A human must ",
        "review and merge any changes.",
        "",
        "## Data audit summary",
        "",
        f"- Total claims: {audit_summary.get('total_claims', '?')}",
        f"- Present: {audit_summary.get('by_status_count', {}).get('present', 0)}",
        f"- Synthetic/PLACEHOLDER: {audit_summary.get('by_status_count', {}).get('synthetic', 0)}",
        f"- Off-repo canonical: {audit_summary.get('by_status_count', {}).get('off-repo', 0)}",
        f"- Partial: {audit_summary.get('by_status_count', {}).get('partial', 0)}",
        f"- Missing: {audit_summary.get('by_status_count', {}).get('missing', 0)}",
        "",
        "## Drift signals",
        "",
    ]
    if not signals:
        lines.append("✅ No drift detected.")
    else:
        for s in signals:
            lines.append(f"- {s}")
    lines.append("")
    lines.append("## Action required")
    lines.append("")
    if not signals:
        lines.append("None. STATUS.md does not need updating.")
    else:
        lines.append("1. Open outputs/data_audit.json and review the missing/partial claims.")
        lines.append(
            "2. Update STATUS.md scorecard if the on-disk state has actually "
            "drifted (e.g., new data downloaded, files moved)."
        )
        lines.append(
            "3. If a paper now claims a dataset it does not have, edit the " "paper text to reflect the actual state."
        )
    lines.append("")
    DRIFT_NOTE.write_text("\n".join(lines))


def append_log(audit_sha: str | None, changed: bool, signal_count: int) -> None:
    WATCHDOG_LOG.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    with WATCHDOG_LOG.open("a") as f:
        f.write(f"timestamp={now} ")
        f.write(f"audit_sha={audit_sha or 'NONE'} ")
        f.write(f"changed={changed} ")
        f.write(f"signals={signal_count}\n")


def emit_prompt() -> str:
    """Emit a self-contained prompt for the cron runner."""
    audit = json.loads(AUDIT_JSON.read_text()) if AUDIT_JSON.exists() else {}
    counts = audit.get("by_status_count", {})
    return (
        "# Thesis sync watchdog prompt\n\n"
        f"Working directory: `{REPO_ROOT}`\n\n"
        "## What this tick does\n\n"
        "Lightweight cross-repo state refresh (every 6 hours):\n"
        "1. Run scripts/validate_data.py\n"
        "2. Detect drift (missing datasets, off-repo paths, synthetic count)\n"
        "3. Write outputs/drift_note.md for human review\n"
        "4. Append to logs/thesis_sync_watchdog.log\n\n"
        "## Current audit state\n\n"
        f"- Present: {counts.get('present', 0)}\n"
        f"- Synthetic: {counts.get('synthetic', 0)}\n"
        f"- Off-repo: {counts.get('off-repo', 0)}\n"
        f"- Missing: {counts.get('missing', 0)}\n"
        f"- Partial: {counts.get('partial', 0)}\n\n"
        "## What to do\n\n"
        "Just run `python3 scripts/thesis_sync_watchdog.py`. "
        "It exits 0 unless the audit itself errored. Do NOT auto-edit STATUS.md.\n\n"
        "If a signal says 'dataset went missing', investigate — it may be a "
        "filesystem issue (mount, permissions, deleted by mistake) or a real "
        "documentation-vs-reality gap.\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Refresh cross-repo state for the satellite-paraguay thesis.")
    parser.add_argument("--check", action="store_true", help="Only check if state changed since last run.")
    parser.add_argument("--emit-prompt", action="store_true", help="Emit a cron-ready prompt.")
    args = parser.parse_args()

    if args.emit_prompt:
        print(emit_prompt())
        return 0

    # Run the audit
    try:
        audit = run_audit()
    except Exception as e:
        print(f"ERROR: audit failed: {e}", file=sys.stderr)
        return 1

    new_sha = _audit_sha()
    prev_sha = _previous_audit_sha()
    changed = new_sha != prev_sha

    # Detect drift
    signals = detect_drift(audit, None)
    write_drift_note(signals, audit)
    append_log(new_sha, changed, len(signals))

    if args.check:
        print(f"changed={changed} signals={len(signals)}")
        return 0

    # Default: print summary
    now = datetime.now(timezone.utc).isoformat(timespec="seconds")
    counts = audit.get("by_status_count", {})
    print(f"[{now}] thesis_sync_watchdog run")
    print(f"  audit_sha: {new_sha}")
    print(f"  changed:    {changed} (prev: {prev_sha or 'none'})")
    print(f"  signals:    {len(signals)}")
    print(
        f"  present={counts.get('present', 0)} synthetic={counts.get('synthetic', 0)} "
        f"off-repo={counts.get('off-repo', 0)} missing={counts.get('missing', 0)}"
    )
    if signals:
        print("\nDrift signals:")
        for s in signals:
            print(f"  {s}")
    print(f"\nDrift note written to: {DRIFT_NOTE}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
